[workspace]
resolver = "3"
members = [ 
  "services/epoch-rewards-tracker",
  "services/cli",
  "stakenet-simulator-db",
  "benchmark"
]

[patch.crates-io.curve25519-dalek]
git = "https://github.com/solana-labs/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"

[workspace.dependencies]
anchor-lang = "0.31.1"
dotenvy = "0.15.7"
regex = "1.11.1"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
solana-account-decoder-client-types = "^2.3"
solana-client = "=2.3.3"
solana-sdk = "=2.3.1"
solana-transaction-status-client-types= "^2.3"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "chrono", "bigdecimal" ] }
stakenet-simulator-db = { path = "./stakenet-simulator-db" }
thiserror = {version = "2.0.12"}
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
validator-history = { package = "validator-history", features = ["no-entrypoint"], git = "https://github.com/jito-foundation/stakenet", branch = "master" }
jito-steward = { package = "jito-steward", features = ["no-entrypoint"], git = "https://github.com/jito-foundation/stakenet", branch = "master" }
reqwest = { version = "0.12", features = ["json"] }
steward-simulator-cli = { path = "./services/cli" }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
