[package]
name = "stakenet-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
thiserror = { workspace = true }
serde = { workspace = true }
clap = { version = "4.5.15", features = ["derive"] }
shlex = "1.3.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "chrono", "bigdecimal" ] }