[package]
name = "stakenet-simulator-db"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "chrono", "bigdecimal" ] }
validator-history = { workspace = true }
